<?php

namespace Database\Seeders;

use App\Models\Role;
use Illuminate\Database\Seeder;

class RoleSeeder extends Seeder
{
    private $roles = [
        [
            'role_name' => 'Agency Head',
            'permissions' => [
                'head:*',
                'account-user:view',
                'account-role:view',
                'account-department:view',
                'account-section:view',
                'company:*',
                'pr:view,create,update,approve,disapprove,approve-rfq,print',
                'rfq:view,print',
                'aoq:view,print',
                'po:view,print',
                'iar:view,print',
                'obr:view,print',
                'dv:view,print',
                'inv-supply:view,print',
                'inv-issuance:view,print',
                'lib-account-class:view',
                'lib-account:view',
                'lib-bid-committee:view',
                'lib-fpp:view',
                'lib-fund-source:view',
                'lib-item-class:view',
                'lib-mode-proc:view',
                'lib-paper-size:*',
                'lib-responsibility-center:view',
                'lib-signatory:*',
                'lib-supplier:view',
                'lib-unit-issue:*',
                'system-log:*',
            ],
        ],
        [
            'role_name' => 'End User',
            'permissions' => [
                'user:*',
                'comapny:view',
                'account-department:view',
                'account-section:view',
                'account-user:view',
                'pr:view,create,update,submit,cancel,print',
                'rfq:view,receive,submit,print',
                'aoq:view,print',
                'po:view,print',
                'iar:view,print',
                'obr:view,print',
                'dv:view,print',
                'lib-fund-source:view',
                'lib-paper-size:view',
                'lib-signatory:view',
                'lib-supplier:view',
                'lib-unit-issue:view',
                'system-log:*',
            ],
        ],
        [
            'role_name' => 'Administrator',
            'permissions' => [
                'super:*',
                'account-user:*',
                'account-role:*',
                'account-department:*',
                'account-section:*',
                'company:*',
                'pr:*',
                'rfq:*',
                'aoq:*',
                'po:*',
                'iar:*',
                'obr:*',
                'dv:*',
                'inv-supply:*',
                'inv-issuance:*',
                'lib-account-class:*',
                'lib-account:*',
                'lib-bid-committee:*',
                'lib-fpp:*',
                'lib-fund-source:*',
                'lib-item-class:*',
                'lib-mode-proc:*',
                'lib-paper-size:*',
                'lib-responsibility-center:*',
                'lib-signatory:*',
                'lib-supplier:*',
                'lib-unit-issue:*',
                'system-log:*',
            ],
        ],
        [
            'role_name' => 'Supply Officer',
            'permissions' => [
                'supply:*',
                'account-section:view',
                'account-user:view',
                'comapny:view',
                'pr:*',
                'rfq:*',
                'aoq:*',
                'po:*',
                'iar:*',
                'obr:view,create,update,pending,print',
                'dv:view,create,update,pending,print',
                'inv-supply:*',
                'inv-issuance:*',
                'lib-account:view',
                'lib-fund-source:*',
                'lib-fpp:view',
                'lib-item-class:*',
                'lib-mode-proc:*',
                'lib-paper-size:*',
                'lib-responsibility-center:view',
                'lib-signatory:*',
                'lib-supplier:*',
                'lib-unit-issue:*',
                'system-log:*',
            ],
        ],
        [
            'role_name' => 'Budget',
            'permissions' => [
                'budget:*',
                'account-section:view',
                'account-user:view',
                'comapny:view',
                'pr:view,create,update,approve-cash-available,cancel,submit,print',
                'rfq:view,print',
                'aoq:view,print',
                'po:view,print',
                'iar:view,print',
                'obr:*',
                'dv:view,print',
                'lib-account-class:*',
                'lib-account:*',
                'lib-fund-source:*',
                'lib-fpp:*',
                'lib-paper-size:*',
                'lib-responsibility-center:*',
                'lib-signatory:*',
                'lib-supplier:view',
                'lib-unit-issue:view',
                'system-log:*',
            ],
        ],
        [
            'role_name' => 'Accountant',
            'permissions' => [
                'accountant:*',
                'account-section:view',
                'account-user:view',
                'comapny:view',
                'pr:view,create,update,approve-cash-available,cancel,submit,print',
                'rfq:view,print',
                'aoq:view,print',
                'po:view,print',
                'iar:view,print',
                'obr:view,print',
                'dv:*',
                'lib-account-class:*',
                'lib-account:*',
                'lib-fund-source:*',
                'lib-fpp:*',
                'lib-paper-size:*',
                'lib-responsibility-center:*',
                'lib-signatory:*',
                'lib-supplier:view',
                'lib-unit-issue:view',
                'system-log:*',
            ],
        ],
        [
            'role_name' => 'Cashier',
            'permissions' => [
                'cashier:*',
                'account-section:view',
                'account-user:view',
                'comapny:view',
                'pr:view,create,update,approve-cash-available,cancel,submit,print',
                'rfq:view,print',
                'aoq:view,print',
                'po:view,print',
                'iar:view,print',
                'obr:view,print',
                'dv:view,uodate,paid,print',
                'payment:*',
                'lib-account-class:*',
                'lib-account:*',
                'lib-fund-source:*',
                'lib-fpp:*',
                'lib-paper-size:*',
                'lib-responsibility-center:*',
                'lib-signatory:*',
                'lib-supplier:view',
                'lib-unit-issue:view',
                'system-log:*',
            ],
        ],
    ];

    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        foreach ($this->roles as $role) {
            Role::create($role);
        }
    }
}
